#!/bin/bash
USERNAME=$(whoami)
MYNAME=$0
MYPWD=$(pwd)
MYDATE=$(date)
REPO=$(pwd | awk -F/ '{print $NF}' | tr '[:upper:]' '[:lower:]')

if ! [[ $GID ]]; then echo set export GID=123456 to set the parent group for the repo; exit 99; fi 
if ! [[ $GROUP ]]; then echo set export GROUP=web to set the parent group name for the repo; exit 99; fi
if ! [[ $TOKEN ]]; then echo set export TOKEN=123455 to set the Gitlab Personal Token; exit 99; fi


echo $MYDATE $USERNAME"@"$MYPWD/$MYNAME  $1 $2 $3

if ! [[ -d ./.git ]]
then
	echo no git dir
else
	git init
	git add .
	git remote add origin git@gitlab.com:pknw1-dev/${GROUP}/${REPO}.git
	git commit -m  "$(date)"
	git push 
fi


curl -H "Content-Type:application/json" https://gitlab.com/api/v4/projects?private_token=$TOKEN -d "{ \"name\": \"$REPO\", \"namespace_id\" : \"$GID\" } "
