#!/bin/bash
apt update
apt-get install -y perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl apt-show-versions python
wget https://datapacket.dl.sourceforge.net/project/webadmin/webmin/1.930/webmin_1.930_all.deb
dpkg -i ./webmin_1.930_all.deb
