#!/bin/bash

if ! [[ -d /home/docker/services ]]; then mkdir -p /home/docker/services; fi
if ! [[ -d /home/docker/scripts ]]; then mkdir -p /home/docker/scripts; fi

wget -O /usr/local/bin/docker-services https://raw.githubusercontent.com/pknw1/public-scripts/master/scripts/docker-services 
chmod +x /usr/local/bin/docker-services
